"""resume language

Revision ID: 1a82d11fa840
Revises: 91a7bcb0dc39
Create Date: 2026-03-22 14:06:50.289691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a82d11fa840'
down_revision: Union[str, None] = '91a7bcb0dc39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experience', 'job_title',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('experience', 'company',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=128),
               nullable=False)
    op.add_column('resume', sa.Column('language', sa.String(length=8), nullable=True))
    op.add_column('resume', sa.Column('is_draft', sa.Boolean(), nullable=True))
    op.add_column('skill', sa.Column('proficiency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'proficiency')
    op.drop_column('resume', 'is_draft')
    op.drop_column('resume', 'language')
    op.alter_column('experience', 'company',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('experience', 'job_title',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###
