"""cv additional fields

Revision ID: 91a7bcb0dc39
Revises: d825ba5705ae
Create Date: 2026-03-22 13:28:34.931228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a7bcb0dc39'
down_revision: Union[str, None] = 'd825ba5705ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('street_address', sa.String(length=100), nullable=True))
    op.add_column('resume', sa.Column('postcode', sa.String(length=16), nullable=True))
    op.add_column('resume', sa.Column('linkedin', sa.Text(), nullable=True))
    op.add_column('resume', sa.Column('website', sa.Text(), nullable=True))
    op.add_column('resume', sa.Column('driving_license', sa.String(length=64), nullable=True))
    op.add_column('resume', sa.Column('nationality', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'nationality')
    op.drop_column('resume', 'driving_license')
    op.drop_column('resume', 'website')
    op.drop_column('resume', 'linkedin')
    op.drop_column('resume', 'postcode')
    op.drop_column('resume', 'street_address')
    # ### end Alembic commands ###
