"""add cv models

Revision ID: b6ef72cde59d
Revises: fd631723f335
Create Date: 2026-01-30 17:36:51.825503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ef72cde59d'
down_revision: Union[str, None] = 'fd631723f335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('template_name', sa.String(length=50), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('professional_title', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('completion', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_resume_user_id'), 'resume', ['user_id'], unique=False)
    op.create_table('certificate',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('resume_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('issue_date', sa.String(length=7), nullable=True),
    sa.Column('expiration_date', sa.String(length=7), nullable=True),
    sa.Column('no_expiry', sa.Boolean(), nullable=False),
    sa.Column('credential_link', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_resume_id'), 'certificate', ['resume_id'], unique=False)
    op.create_table('custom_section',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('resume_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.String(length=7), nullable=True),
    sa.Column('end_date', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_section_resume_id'), 'custom_section', ['resume_id'], unique=False)
    op.create_table('education',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('resume_id', sa.BigInteger(), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('degree', sa.String(length=150), nullable=True),
    sa.Column('field_of_study', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.String(length=7), nullable=True),
    sa.Column('end_date', sa.String(length=7), nullable=True),
    sa.Column('currently_studying', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_resume_id'), 'education', ['resume_id'], unique=False)
    op.create_table('experience',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('resume_id', sa.BigInteger(), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('employment_type', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.String(length=7), nullable=True),
    sa.Column('end_date', sa.String(length=7), nullable=True),
    sa.Column('currently_working', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_resume_id'), 'experience', ['resume_id'], unique=False)
    op.create_table('language',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('resume_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('proficiency', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_resume_id'), 'language', ['resume_id'], unique=False)
    op.create_table('skill',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('resume_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_resume_id'), 'skill', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_resume_id'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_language_resume_id'), table_name='language')
    op.drop_table('language')
    op.drop_index(op.f('ix_experience_resume_id'), table_name='experience')
    op.drop_table('experience')
    op.drop_index(op.f('ix_education_resume_id'), table_name='education')
    op.drop_table('education')
    op.drop_index(op.f('ix_custom_section_resume_id'), table_name='custom_section')
    op.drop_table('custom_section')
    op.drop_index(op.f('ix_certificate_resume_id'), table_name='certificate')
    op.drop_table('certificate')
    op.drop_index(op.f('ix_resume_user_id'), table_name='resume')
    op.drop_table('resume')
    # ### end Alembic commands ###
