"""replace_location_with_country_city

Revision ID: d825ba5705ae
Revises: b6ef72cde59d
Create Date: 2026-02-21 18:23:21.463024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd825ba5705ae'
down_revision: Union[str, None] = 'b6ef72cde59d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('resume', sa.Column('city', sa.String(length=100), nullable=True))
    op.drop_column('resume', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('location', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('resume', 'city')
    op.drop_column('resume', 'country')
    # ### end Alembic commands ###
